# Generated by Django 4.2.9 on 2024-11-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("web", "0020_demorequest_attempt_demorequest_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="TestLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("LKG", "LKG"),
                            ("UKG", "UKG"),
                            ("1", "Class 1"),
                            ("2", "Class 2"),
                            ("3", "Class 3"),
                            ("4", "Class 4"),
                            ("5", "Class 5"),
                            ("6", "Class 6"),
                            ("7", "Class 7"),
                            ("8", "Class 8"),
                            ("9", "Class 9"),
                            ("10", "Class 10"),
                            ("11", "Class 11"),
                            ("12", "Class 12"),
                        ],
                        max_length=10,
                    ),
                ),
                ("link", models.URLField()),
                ("board", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.board")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="smartest.subject")),
            ],
        ),
    ]
