# Generated by Django 4.2.9 on 2024-10-01 21:25

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import django_countries.fields
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("logo", models.ImageField(blank=True, null=True, upload_to="program/")),
                ("image", models.ImageField(upload_to="program/")),
                ("is_active", models.BooleanField(default=True)),
                ("content", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ("course_fee", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("duration", models.CharField(blank=True, max_length=200, null=True)),
                ("age_group", models.CharField(choices=[("3-5", "3-5 Years"), ("6-9", "6-9 Years"), ("10-13", "10-13 Years"), ("14-18", "14-18 Years")], max_length=200)),
                ("lessons", models.IntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=200, null=True)),
                ("level", models.CharField(blank=True, max_length=200, null=True)),
                ("is_certificate_included", models.BooleanField(blank=True, default=True, null=True)),
                ("preview_video_id", models.CharField(blank=True, max_length=11, null=True)),
                ("show_in_navigation", models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                "verbose_name": "Program & Course",
                "verbose_name_plural": "Programs & Courses",
                "db_table": "web_program",
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="achievement/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "template",
                    models.CharField(
                        choices=[("web/blog_detail_1.html", "Default"), ("web/blog_detail_2.html", "Elegant"), ("web/blog_detail_3.html", "Classic")],
                        default="web/blog_detail_1.html",
                        max_length=200,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("date", models.DateField()),
                ("summary", models.TextField()),
                ("image", models.ImageField(upload_to="blog/")),
                ("meta_title", models.CharField(max_length=200)),
                ("meta_description", models.TextField()),
                ("sequence", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="BlogAuthor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="author/")),
                ("bio", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Blog Author",
                "verbose_name_plural": "Blog Authors",
            },
        ),
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Categories",
            },
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("logo", models.ImageField(upload_to="board/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Board",
                "verbose_name_plural": "Boards",
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="club/image/")),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Club",
                "verbose_name_plural": "Clubs",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("whatsapp", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(verbose_name="Your message")),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="DemoRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("raised_by", models.CharField(choices=[("STUDENT", "Student"), ("PARENT", "Parent"), ("GUARDIAN", "Guardian")], max_length=200, verbose_name="I'am a")),
                ("student_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("phone_number", models.CharField(max_length=20)),
                ("whatsapp_number", models.CharField(max_length=20)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("LKG", "LKG"),
                            ("UKG", "UKG"),
                            ("1", "Class 1"),
                            ("2", "Class 2"),
                            ("3", "Class 3"),
                            ("4", "Class 4"),
                            ("5", "Class 5"),
                            ("6", "Class 6"),
                            ("7", "Class 7"),
                            ("8", "Class 8"),
                            ("9", "Class 9"),
                            ("10", "Class 10"),
                            ("11", "Class 11"),
                            ("12", "Class 12"),
                        ],
                        max_length=200,
                        verbose_name="Class",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=200)),
            ],
            options={
                "verbose_name": "Demo Request",
                "verbose_name_plural": "Demo Requests",
            },
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("phone", models.CharField(max_length=15)),
                ("whatsapp", models.CharField(max_length=15)),
                ("message", models.TextField(verbose_name="Drop your message here")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Enquiry",
                "verbose_name_plural": "Enquiries",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "General FAQ",
                "verbose_name_plural": "General FAQs",
            },
        ),
        migrations.CreateModel(
            name="GeneralFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "General Feature",
                "verbose_name_plural": "General Features",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "template",
                    models.CharField(
                        choices=[("web/location_1.html", "Default"), ("web/location_2.html", "Elegant"), ("web/location_3.html", "Classic")],
                        default="web/location_1.html",
                        max_length=200,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("banner_image", models.ImageField(upload_to="location/")),
                ("page_title", models.CharField(max_length=200)),
                ("meta_title", models.CharField(max_length=200)),
                ("meta_description", models.TextField()),
                ("content", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("show_in_navigation", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.CreateModel(
            name="MediaFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="feature/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Media Feature",
                "verbose_name_plural": "Media Features",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("date", models.DateField()),
                ("summary", models.TextField()),
                ("image", models.ImageField(upload_to="blog/")),
                ("content", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ("meta_title", models.CharField(max_length=200)),
                ("meta_description", models.TextField()),
                ("sequence", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "ordering": ("sequence", "-date"),
            },
        ),
        migrations.CreateModel(
            name="NonAcademicProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("logo", models.ImageField(blank=True, null=True, upload_to="program/")),
                ("image", models.ImageField(upload_to="program/")),
                ("program_type", models.CharField(choices=[("CLUB", "Club Courses"), ("NON_ACADEMIC", "Non Academic Courses")], default="ACADEMIC", max_length=200)),
                ("content", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ("course_fee", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("duration", models.CharField(blank=True, max_length=200, null=True)),
                ("age_group", models.CharField(choices=[("3-5", "3-5 Years"), ("6-9", "6-9 Years"), ("10-13", "10-13 Years"), ("14-18", "14-18 Years")], max_length=200)),
                ("lessons", models.IntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=200, null=True)),
                ("level", models.CharField(blank=True, max_length=200, null=True)),
                ("is_certificate_included", models.BooleanField(blank=True, default=True, null=True)),
                ("preview_video_id", models.CharField(blank=True, max_length=11, null=True)),
                ("show_in_navigation", models.BooleanField(blank=True, default=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Program & Course",
                "verbose_name_plural": "Programs & Courses",
            },
        ),
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Resource Category",
                "verbose_name_plural": "Resource Categories",
            },
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="slider/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Slider",
                "verbose_name_plural": "Sliders",
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("bi-instagram", "Instagram"),
                            ("bi-facebook", "Facebook"),
                            ("bi-youtube", "Youtube"),
                            ("bi-pinterest", "Pinterest"),
                            ("bi-twitter", "Twitter"),
                            ("bi-threads", "Threads"),
                            ("bi-tiktok", "Tiktok"),
                            ("bi-wikipedia", "Wikipedia"),
                            ("bi-google", "Google"),
                            ("bi-google-play", "Google Play"),
                            ("bi-github", "github"),
                            ("bi-xbox", "X Box"),
                        ],
                        max_length=200,
                    ),
                ),
                ("url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Media",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                ("image", models.ImageField(upload_to="staff/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staffs",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=200)),
                ("icon", models.ImageField(upload_to="subject/")),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("banner_image", models.ImageField(upload_to="subject/")),
                ("page_title", models.CharField(max_length=200)),
                ("meta_title", models.CharField(max_length=200)),
                ("page_description", models.TextField()),
                ("meta_description", models.TextField()),
                ("content", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("show_in_navigation", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="testimonial/")),
                ("content", models.TextField()),
                ("video_id", models.CharField(max_length=11)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
        migrations.CreateModel(
            name="SubjectFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.subject")),
            ],
            options={
                "verbose_name": "Subject Detail",
                "verbose_name_plural": "Subject Details",
            },
        ),
        migrations.CreateModel(
            name="SubjectFAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.subject")),
            ],
            options={
                "verbose_name": "Subject FAQ",
                "verbose_name_plural": "Subject FAQs",
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="resource/")),
                ("is_active", models.BooleanField(default=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.resourcecategory")),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
            },
        ),
        migrations.CreateModel(
            name="ProgramFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.academicprogram")),
            ],
            options={
                "verbose_name": "Program Feature",
                "verbose_name_plural": "Program Features",
            },
        ),
        migrations.CreateModel(
            name="ProgramFAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.academicprogram")),
            ],
            options={
                "verbose_name": "Program FAQ",
                "verbose_name_plural": "Program FAQs",
            },
        ),
        migrations.CreateModel(
            name="ProgramBenefit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.academicprogram")),
            ],
            options={
                "verbose_name": "Program Benefit",
                "verbose_name_plural": "Program Benefits",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("student_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("state", models.CharField(max_length=200, verbose_name="State/Province")),
                ("phone_number", models.CharField(max_length=20)),
                ("whatsapp_number", models.CharField(max_length=20)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("LKG", "LKG"),
                            ("UKG", "UKG"),
                            ("1", "Class 1"),
                            ("2", "Class 2"),
                            ("3", "Class 3"),
                            ("4", "Class 4"),
                            ("5", "Class 5"),
                            ("6", "Class 6"),
                            ("7", "Class 7"),
                            ("8", "Class 8"),
                            ("9", "Class 9"),
                            ("10", "Class 10"),
                            ("11", "Class 11"),
                            ("12", "Class 12"),
                        ],
                        max_length=200,
                        verbose_name="Class",
                    ),
                ),
                ("referred_by", models.CharField(max_length=200)),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(blank=True, max_length=200, null=True)),
                ("razorpay_order_id", models.CharField(blank=True, max_length=200, null=True)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=200, null=True)),
                ("razorpay_signature", models.CharField(blank=True, max_length=200, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("course", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="web.nonacademicprogram")),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.CreateModel(
            name="LocationFAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.location")),
            ],
            options={
                "verbose_name": "Location FAQ",
                "verbose_name_plural": "Location FAQs",
            },
        ),
        migrations.CreateModel(
            name="BlogContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("content", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ("blog", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.blog")),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.blogauthor"),
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.blogcategory"),
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=taggit.managers.TaggableManager(blank=True, help_text="A comma-separated list of tags.", through="taggit.TaggedItem", to="taggit.Tag", verbose_name="Tags"),
        ),
        migrations.CreateModel(
            name="AuthorSocialMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("bi-instagram", "Instagram"),
                            ("bi-facebook", "Facebook"),
                            ("bi-youtube", "Youtube"),
                            ("bi-pinterest", "Pinterest"),
                            ("bi-twitter", "Twitter"),
                            ("bi-threads", "Threads"),
                            ("bi-tiktok", "Tiktok"),
                            ("bi-wikipedia", "Wikipedia"),
                            ("bi-google", "Google"),
                            ("bi-google-play", "Google Play"),
                            ("bi-github", "github"),
                            ("bi-xbox", "X Box"),
                        ],
                        max_length=200,
                    ),
                ),
                ("url", models.URLField()),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.blogauthor")),
            ],
            options={
                "verbose_name": "Author Social Media",
                "verbose_name_plural": "Author Social Media",
            },
        ),
    ]
