# Generated by Django 4.2.9 on 2024-10-01 23:33

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicprogram",
            options={},
        ),
        migrations.AlterModelOptions(
            name="nonacademicprogram",
            options={},
        ),
        migrations.RemoveField(
            model_name="academicprogram",
            name="course_fee",
        ),
        migrations.RemoveField(
            model_name="academicprogram",
            name="is_certificate_included",
        ),
        migrations.RemoveField(
            model_name="academicprogram",
            name="level",
        ),
        migrations.RemoveField(
            model_name="nonacademicprogram",
            name="level",
        ),
        migrations.RemoveField(
            model_name="nonacademicprogram",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="nonacademicprogram",
            name="show_in_navigation",
        ),
        migrations.AddField(
            model_name="nonacademicprogram",
            name="learning_overview",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name="Learning Overview"),
        ),
        migrations.AlterField(
            model_name="nonacademicprogram",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name="About"),
        ),
        migrations.AlterField(
            model_name="nonacademicprogram",
            name="course_fee",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name="academicprogram",
            table=None,
        ),
        migrations.CreateModel(
            name="NonAcademicProgramTime",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.CharField(max_length=200)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.nonacademicprogram")),
            ],
            options={
                "verbose_name": "Program Time",
                "verbose_name_plural": "Program Times",
            },
        ),
    ]
