# Generated by Django 4.2.9 on 2024-10-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.ForeignKey(default=402, on_delete=django.db.models.deletion.CASCADE, to="web.country"),
            preserve_default=False,
        ),
    ]
