# Generated by Django 4.2.9 on 2024-10-03 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_location_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorsocialmedia",
            name="icon",
            field=models.CharField(
                choices=[
                    ("bi-instagram", "Instagram"),
                    ("bi-facebook", "Facebook"),
                    ("bi-youtube", "Youtube"),
                    ("bi-pinterest", "Pinterest"),
                    ("bi-twitter", "Twitter"),
                    ("bi-threads", "Threads"),
                    ("bi-tiktok", "Tiktok"),
                    ("bi-wikipedia", "Wikipedia"),
                    ("bi-google", "Google"),
                    ("bi-google-play", "Google Play"),
                    ("bi-github", "github"),
                    ("bi-xbox", "X Box"),
                    ("bi-linkedin", "Linkedin"),
                    ("bi-youtube", "Youtube"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="locations", to="web.country"),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="icon",
            field=models.CharField(
                choices=[
                    ("bi-instagram", "Instagram"),
                    ("bi-facebook", "Facebook"),
                    ("bi-youtube", "Youtube"),
                    ("bi-pinterest", "Pinterest"),
                    ("bi-twitter", "Twitter"),
                    ("bi-threads", "Threads"),
                    ("bi-tiktok", "Tiktok"),
                    ("bi-wikipedia", "Wikipedia"),
                    ("bi-google", "Google"),
                    ("bi-google-play", "Google Play"),
                    ("bi-github", "github"),
                    ("bi-xbox", "X Box"),
                    ("bi-linkedin", "Linkedin"),
                    ("bi-youtube", "Youtube"),
                ],
                max_length=200,
            ),
        ),
    ]
