# Generated by Django 4.2.9 on 2024-10-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_alter_authorsocialmedia_icon_alter_location_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "About",
            },
        ),
    ]
