# Generated by Django 4.2.9 on 2024-10-04 11:20

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_about"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="show_in_navigation",
            new_name="show_in_page",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="show_in_navigation",
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("page_title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("meta_title", models.CharField(max_length=200)),
                ("meta_description", models.TextField()),
                ("content", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("show_in_page", models.BooleanField(default=True, verbose_name="Show in Location Page")),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cities", to="web.location")),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
            },
        ),
    ]
