# Generated by Django 4.2.9 on 2024-10-04 11:40

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_rename_show_in_navigation_location_show_in_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="board",
            name="page_title",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="board",
            name="slug",
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
    ]
