# Generated by Django 4.2.9 on 2024-10-04 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_board_content_board_page_title_board_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogFAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                ("blog", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.blog")),
            ],
            options={
                "verbose_name": "Blog FAQ",
                "verbose_name_plural": "Blog FAQs",
            },
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.RemoveField(
            model_name="enquiry",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="enquiry",
            name="whatsapp",
        ),
        migrations.AddField(
            model_name="enquiry",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="phone_number",
            field=models.CharField(default=1, max_length=15, verbose_name="Phone Number"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enquiry",
            name="whatsapp_number",
            field=models.CharField(default=1, max_length=15, verbose_name="Whatsapp Number"),
            preserve_default=False,
        ),
    ]
