# Generated by Django 4.2.9 on 2024-10-11 14:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_blogfaq_delete_contact_remove_enquiry_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicprogram",
            name="age_group",
        ),
        migrations.RemoveField(
            model_name="nonacademicprogram",
            name="age_group",
        ),
        migrations.AddField(
            model_name="nonacademicprogram",
            name="age_groups",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("3-5", "3-5 Years"), ("6-9", "6-9 Years"), ("10-13", "10-13 Years"), ("14-18", "14-18 Years")], default="3-5", max_length=200
            ),
            preserve_default=False,
        ),
    ]
