# Generated by Django 4.2.9 on 2024-10-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_remove_academicprogram_age_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicprogram",
            name="meta_description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academicprogram",
            name="meta_title",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nonacademicprogram",
            name="meta_description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nonacademicprogram",
            name="meta_title",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
