# Generated by Django 4.2.9 on 2024-10-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0011_academicprogram_meta_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demorequest",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="utm_content",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="utm_medium",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="utm_source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="utm_term",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="utm_content",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="utm_medium",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="utm_source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="utm_term",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
