# Generated by Django 4.2.9 on 2024-10-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_demorequest_utm_campaign_demorequest_utm_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonacademicprogram",
            name="show_learning_overview",
            field=models.BooleanField(default=True, verbose_name="Show Learning Overview"),
        ),
    ]
