# Generated by Django 4.2.9 on 2024-10-20 06:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0013_nonacademicprogram_show_learning_overview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Drop your message here"),
        ),
        migrations.AlterField(
            model_name="nonacademicprogram",
            name="age_groups",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("3-5", "3-5 Years"), ("6-9", "6-9 Years"), ("10-13", "10-13 Years"), ("14-18", "14-18 Years"), ("18-20", "18-20 Years"), ("20P", "20 Plus Years")],
                max_length=200,
            ),
        ),
    ]
