# Generated by Django 4.2.9 on 2024-10-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0015_alter_nonacademicprogram_age_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="phone_number",
            field=models.CharField(max_length=25, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="whatsapp_number",
            field=models.CharField(max_length=25, verbose_name="Whatsapp Number"),
        ),
    ]
