# Generated by Django 4.2.9 on 2024-10-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0016_alter_enquiry_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="whatsapp",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
