# Generated by Django 4.2.9 on 2024-10-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0017_about_whatsapp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
