# Generated by Django 4.2.9 on 2024-10-26 10:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0018_alter_city_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="demorequest",
            name="is_sent2crm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="otp_number",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="is_sent2crm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="otp_number",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="Coupon Name")),
                ("code", models.CharField(max_length=200, unique=True, verbose_name="Coupon Code")),
                ("discount", models.DecimalField(decimal_places=2, help_text="Enter discount in percentage", max_digits=10)),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("applicable_courses", models.ManyToManyField(blank=True, to="web.nonacademicprogram")),
            ],
        ),
        migrations.AddField(
            model_name="payment",
            name="coupon",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="web.coupon"),
        ),
    ]
