# Generated by Django 4.2.9 on 2024-10-26 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0019_demorequest_is_sent2crm_demorequest_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demorequest",
            name="attempt",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="attempt",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
