# Generated by Django 4.2.9 on 2024-11-11 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0020_demorequest_attempt_demorequest_token_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcontent",
            options={"ordering": ["id"], "verbose_name": "Blog Content", "verbose_name_plural": "Blog Contents"},
        ),
    ]
