# Generated by Django 4.2.9 on 2024-11-11 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0021_alter_blogcontent_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Club",
        ),
    ]
