# Generated by Django 4.2.9 on 2024-11-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0022_delete_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="about",
            name="whatsapp",
            field=models.CharField(max_length=20, verbose_name="WhatsApp Number"),
        ),
        migrations.AlterField(
            model_name="demorequest",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="demorequest",
            name="whatsapp_number",
            field=models.CharField(max_length=20, verbose_name="WhatsApp Number"),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="whatsapp_number",
            field=models.CharField(max_length=25, verbose_name="WhatsApp Number"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="whatsapp_number",
            field=models.CharField(max_length=20, verbose_name="WhatsApp Number"),
        ),
    ]
