# Generated by Django 4.2.9 on 2024-12-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0023_alter_about_phone_alter_about_whatsapp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="feature_heading",
            field=models.CharField(default="Key Features of Our Tailored Learning Experience", max_length=200),
        ),
    ]
