# Generated by Django 4.2.9 on 2024-12-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0024_subject_feature_heading"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("home_meta_title", "Home Page Meta Title"),
                            ("home_meta_desc", "Home Page Meta Description"),
                            ("about_meta_title", "About Page Meta Title"),
                            ("about_meta_desc", "About Page Meta Description"),
                            ("blogs_meta_title", "Blogs Page Meta Title"),
                            ("blogs_meta_desc", "Blogs Page Meta Description"),
                            ("boards_meta_title", "Boards Page Meta Title"),
                            ("boards_meta_desc", "Boards Page Meta Description"),
                            ("clubs_meta_title", "Clubs Page Meta Title"),
                            ("clubs_meta_desc", "Clubs Page Meta Description"),
                            ("news_meta_title", "News Page Meta Title"),
                            ("news_meta_desc", "News Page Meta Description"),
                            ("nonacademics_meta_title", "Nonacademics Page Meta Title"),
                            ("nonacademics_meta_desc", "Nonacademics Page Meta Description"),
                            ("subjects_meta_title", "Subjects Page Meta Title"),
                            ("subjects_meta_desc", "Subjects Page Meta Description"),
                            ("testimonials_meta_title", "Testimonials Page Meta Title"),
                            ("testimonials_meta_desc", "Testimonials Page Meta Description"),
                            ("contact_meta_title", "Contact Page Meta Title"),
                            ("contact_meta_desc", "Contact Page Meta Description"),
                            ("countries_meta_title", "Countries Page Meta Title"),
                            ("countries_meta_desc", "Countries Page Meta Description"),
                            ("courses_meta_title", "Courses Page Meta Title"),
                            ("courses_meta_desc", "Courses Page Meta Description"),
                            ("downloads_meta_title", "Downloads Page Meta Title"),
                            ("downloads_meta_desc", "Downloads Page Meta Description"),
                        ],
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("value", models.TextField()),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configurations",
            },
        ),
    ]
