# Generated by Django 4.2.9 on 2025-01-12 09:19

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0025_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("phone_number", models.CharField(max_length=25, verbose_name="Phone Number")),
                ("whatsapp_number", models.CharField(max_length=25, verbose_name="WhatsApp Number")),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("message", models.TextField(blank=True, null=True, verbose_name="Drop your message here")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("utm_source", models.CharField(blank=True, max_length=255, null=True)),
                ("utm_medium", models.CharField(blank=True, max_length=255, null=True)),
                ("utm_campaign", models.CharField(blank=True, max_length=255, null=True)),
                ("utm_content", models.CharField(blank=True, max_length=255, null=True)),
                ("utm_term", models.CharField(blank=True, max_length=255, null=True)),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("otp_number", models.CharField(blank=True, max_length=6, null=True)),
                ("attempt", models.IntegerField(default=0)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_sent2crm", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact Data",
                "verbose_name_plural": "Contact Datas",
            },
        ),
    ]
