# Generated by Django 4.2.9 on 2025-01-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0026_contactdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="referred_by",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
