# Generated by Django 4.2.9 on 2025-02-10 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0027_alter_payment_referred_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purpose",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Purpose",
                "verbose_name_plural": "Purposes",
            },
        ),
        migrations.AddField(
            model_name="contactdata",
            name="purpose",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="web.purpose"),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="purpose",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="web.purpose"),
        ),
    ]
