# Generated by Django 4.2.9 on 2025-02-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0028_purpose_contactdata_purpose_enquiry_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicprogram",
            name="program_type",
            field=models.CharField(choices=[("ACADEMIC", "ACADEMIC COURSE"), ("LANGUAGE", "LANGUAGE COURSE")], default="ACADEMIC", max_length=200),
        ),
    ]
