# Generated by Django 5.1.7 on 2025-05-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_alter_configuration_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='key',
            field=models.CharField(choices=[('home_meta_title', 'Home Page Meta Title'), ('home_meta_desc', 'Home Page Meta Description'), ('about_meta_title', 'About Page Meta Title'), ('about_meta_desc', 'About Page Meta Description'), ('blogs_meta_title', 'Blogs Page Meta Title'), ('blogs_meta_desc', 'Blogs Page Meta Description'), ('boards_meta_title', 'Boards Page Meta Title'), ('boards_meta_desc', 'Boards Page Meta Description'), ('clubs_meta_title', 'Clubs Page Meta Title'), ('clubs_meta_desc', 'Clubs Page Meta Description'), ('news_meta_title', 'News Page Meta Title'), ('news_meta_desc', 'News Page Meta Description'), ('nonacademics_meta_title', 'Nonacademics Page Meta Title'), ('nonacademics_meta_desc', 'Nonacademics Page Meta Description'), ('subjects_meta_title', 'Subjects Page Meta Title'), ('subjects_meta_desc', 'Subjects Page Meta Description'), ('testimonials_meta_title', 'Testimonials Page Meta Title'), ('testimonials_meta_desc', 'Testimonials Page Meta Description'), ('contact_meta_title', 'Contact Page Meta Title'), ('contact_meta_desc', 'Contact Page Meta Description'), ('countries_meta_title', 'Countries Page Meta Title'), ('countries_meta_desc', 'Countries Page Meta Description'), ('courses_meta_title', 'Courses Page Meta Title'), ('courses_meta_desc', 'Courses Page Meta Description'), ('downloads_meta_title', 'Downloads Page Meta Title'), ('downloads_meta_desc', 'Downloads Page Meta Description'), ('tools_meta_title', 'Tools Page Meta Title'), ('tools_meta_desc', 'Tools Page Meta Description'), ('cbse_calculator_meta_title', 'CBSE Calculator Page Meta Title'), ('cbse_calculator_meta_desc', 'CBSE Calculator Page Meta Description'), ('sslc_calculator_meta_title', 'SSLC Calculator Page Meta Title'), ('sslc_calculator_meta_desc', 'SSLC Calculator Page Meta Description'), ('cbse_calculator_12_meta_title', 'CBSE 12 Calculator Page Meta Title'), ('cbse_calculator_12_meta_desc', 'CBSE 12 Calculator Page Meta Description'), ('kerala_hsc_calculator_meta_title', 'Kerala HSC Calculator Page Meta Title'), ('kerala_hsc_calculator_meta_desc', 'Kerala HSC Calculator Page Meta Description'), ('tamilnadu_hsc_calculator_meta_title', 'Tamilnadu HSC Calculator Page Meta Title'), ('tamilnadu_hsc_calculator_meta_desc', 'Tamilnadu HSC Calculator Page Meta Description')], max_length=200, unique=True),
        ),
    ]
