# Generated by Django 5.1.7 on 2025-05-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_enquiry_lsq_exception_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='lsq_exception_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='lsq_exception_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='lsq_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='lsq_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
