# Generated by Django 5.1.7 on 2025-05-20 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_alter_configuration_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blog/')),
                ('xpath', models.CharField(help_text='XPath of the element after which the CTA should be shown', max_length=300)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.blog')),
            ],
            options={
                'verbose_name': 'Blog CTA',
                'verbose_name_plural': 'Blog CTAs',
            },
        ),
    ]
