# Generated by Django 5.1.7 on 2025-05-28 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_blogcta'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='news/')),
                ('xpath', models.CharField(help_text='XPath of the element after which the CTA should be shown', max_length=300)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.news')),
            ],
            options={
                'verbose_name': 'News CTA',
                'verbose_name_plural': 'News CTAs',
            },
        ),
    ]
