# Generated by Django 5.1.7 on 2025-06-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_newscta'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='enable_redirect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purpose',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
