# Generated by Django 4.2.9 on 2025-07-31 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0038_purpose_enable_redirect_purpose_redirect_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="NonAcademicProgramCTA",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="NonAcademicProgramCTA/")),
                ("xpath", models.CharField(help_text="XPath of the element after which the CTA should be shown", max_length=300)),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.nonacademicprogram")),
            ],
            options={
                "verbose_name": "Non Academic Program CTA",
                "verbose_name_plural": "Non Academic Program CTAs",
            },
        ),
        migrations.CreateModel(
            name="LocationCTA",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="locations/")),
                ("xpath", models.CharField(help_text="XPath of the element after which the CTA should be shown", max_length=300)),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.location")),
            ],
            options={
                "verbose_name": "Location CTA",
                "verbose_name_plural": "Location CTAs",
            },
        ),
        migrations.CreateModel(
            name="AcademicProgramCTA",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="AcademicProgramCTA/")),
                ("xpath", models.CharField(help_text="XPath of the element after which the CTA should be shown", max_length=300)),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.academicprogram")),
            ],
            options={
                "verbose_name": "Academic Program CTA",
                "verbose_name_plural": "Academic Program CTAs",
            },
        ),
    ]
