# Generated by Django 4.0.3 on 2022-06-14 06:59

import uuid

import tinymce.models
import versatileimagefield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", tinymce.models.HTMLField()),
                ("phone_number", models.CharField(max_length=20)),
                ("phone_number2", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField()),
                ("little_genie_title", models.CharField(max_length=250)),
                ("little_genie_description", tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("child_name", models.CharField(max_length=250)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(max_length=30)),
                ("message", models.TextField(blank=True, null=True)),
                ("is_checked", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=350)),
                ("answer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=250)),
                ("image", versatileimagefield.fields.VersatileImageField(upload_to="", verbose_name="Image")),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(upload_to="images/Gallery", verbose_name="Image"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Social",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.IntegerField(unique=True)),
                ("icon", models.FileField(upload_to="images/SocialMediaIcons")),
                ("link", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"verbose_name": "Social Media", "verbose_name_plural": "Social Medias", "ordering": ("order",)},
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="images/Testimonials", verbose_name="Image"
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
