# Generated by Django 4.0.3 on 2022-06-14 06:59

import uuid

import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("Academic", "Academic"), ("Non-Academic", "Non-Academic")], max_length=250
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(upload_to="images/course", verbose_name="Image"),
                ),
                ("description", models.TextField()),
                ("course_duration", models.CharField(max_length=250)),
                ("course_fee", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="CourseEnquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("child_name", models.CharField(max_length=250)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(max_length=30)),
                ("message", models.TextField(blank=True, null=True)),
                ("is_checked", models.BooleanField(default=False)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course.course")),
            ],
        ),
    ]
