# Generated by Django 4.0.3 on 2022-06-14 06:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("course", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="courseenquiry",
            name="name",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        )
    ]
