# Generated by Django 4.0.3 on 2022-06-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("course", "0002_courseenquiry_name")]

    operations = [migrations.RemoveField(model_name="courseenquiry", name="name")]
