# Generated by Django 4.0.3 on 2023-01-27 22:52

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("course", "0003_remove_courseenquiry_name")]

    operations = [
        migrations.AddField(
            model_name="courseenquiry",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        )
    ]
