# Generated by Django 4.0.3 on 2022-06-14 06:59

import versatileimagefield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(upload_to="images/team", verbose_name="Image"),
                ),
                ("name", models.CharField(max_length=250)),
                ("designation", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("facebook_url", models.URLField(blank=True, max_length=250, null=True)),
                ("twitter_url", models.URLField(blank=True, max_length=250, null=True)),
                ("linkedin_url", models.URLField(blank=True, max_length=250, null=True)),
                ("instagram_url", models.URLField(blank=True, max_length=250, null=True)),
            ],
        )
    ]
