# Generated by Django 4.0.3 on 2022-06-14 06:59

import uuid

import django.db.models.deletion
import tinymce.models
import versatileimagefield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("designation", models.CharField(max_length=250)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("photo", models.ImageField(upload_to="images/authors")),
                ("about", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(upload_to="images/Blog", verbose_name="Image"),
                ),
                ("published_date", models.DateField(verbose_name="published date(yyyy-mm-dd)")),
                ("published_time", models.TimeField(verbose_name="published time(hh:mm:ss)")),
                ("summary", models.TextField()),
                ("content", tinymce.models.HTMLField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="blogs.author")),
            ],
        ),
    ]
