# Generated by Django 4.2.9 on 2024-08-07 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=200)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="airlines")),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Airline",
                "verbose_name_plural": "Airlines",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Asia Pacific", "Asia Pacific"),
                            ("Europe", "Europe"),
                            ("Middle East and Africa", "Middle East and Africa"),
                            ("North Asia", "North Asia"),
                            ("The Americas", "The Americas"),
                        ],
                        max_length=200,
                    ),
                ),
                ("city", models.CharField(max_length=200, verbose_name="City/Area")),
                ("airport_code", models.CharField(max_length=200)),
                ("ns24_level", models.CharField(blank=True, max_length=200, null=True, verbose_name="NS24 Level")),
                ("nw24_level", models.CharField(blank=True, max_length=200, null=True, verbose_name="NW24 Level")),
                ("ns25_level", models.CharField(blank=True, max_length=200, null=True, verbose_name="NS25 Level")),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Airport",
                "verbose_name_plural": "Airports",
                "ordering": ("city",),
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("address", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=200)),
                ("flag", models.URLField()),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=200, unique=True)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="states", to="main.country")),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
                "ordering": ("name",),
            },
        ),
    ]
