# Generated by Django 4.2.9 on 2024-08-13 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airport",
            name="country",
        ),
        migrations.RemoveField(
            model_name="airport",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="district",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="district",
            name="state",
        ),
        migrations.RemoveField(
            model_name="state",
            name="country",
        ),
        migrations.RemoveField(
            model_name="state",
            name="creator",
        ),
        migrations.DeleteModel(
            name="Airline",
        ),
        migrations.DeleteModel(
            name="Airport",
        ),
        migrations.DeleteModel(
            name="Branch",
        ),
        migrations.DeleteModel(
            name="District",
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
