# Generated by Django 4.2.9 on 2024-09-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_standard_student_subject_teacher_delete_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
