# Generated by Django 4.2.9 on 2024-09-30 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_student_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="standard",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subjects", to="main.standard"),
        ),
    ]
