# Generated by Django 4.2.9 on 2025-01-12 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_syllabus_subject_syllabus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="syllabus",
            field=models.ForeignKey(default="f47cdb41-1e25-45d4-9c5a-ecc2e7c98337", on_delete=django.db.models.deletion.CASCADE, related_name="subjects", to="main.syllabus"),
            preserve_default=False,
        ),
    ]
