# Generated by Django 4.2.9 on 2024-09-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="users/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="usertype",
            field=models.CharField(choices=[("Administrator", "Administrator"), ("Teacher", "Teacher"), ("Student", "Student")], default="Student", max_length=20),
        ),
    ]
