# Generated by Django 4.2.9 on 2024-09-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_photo_alter_customuser_usertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(default="users/avatar.png", upload_to="users/"),
        ),
    ]
