# Generated by Django 4.2.9 on 2024-10-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(blank=True, default="users/avatar.png", null=True, upload_to="users/"),
        ),
    ]
