# Generated by Django 4.2.9 on 2024-09-25 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_assignment_classtest_event_delete_application"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="standard",
        ),
        migrations.RemoveField(
            model_name="classtest",
            name="standard",
        ),
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateField(default=datetime.datetime(2024, 9, 25, 22, 57, 35, 794127, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
