# Generated by Django 4.2.9 on 2024-09-26 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_standard_student_subject_teacher_delete_country"),
        ("web", "0003_remove_assignment_standard_remove_classtest_standard_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="assigned_to",
            field=models.ManyToManyField(blank=True, to="main.student"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="created_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignment_created_by", to="main.teacher"),
        ),
    ]
