# Generated by Django 4.2.9 on 2024-09-26 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_student_student_id"),
        ("web", "0004_assignment_assigned_to_alter_assignment_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="assignment_id",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classtest",
            name="test_id",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="classtest",
            name="created_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="class_test_created_by", to="main.teacher"),
        ),
    ]
