# Generated by Django 4.2.9 on 2024-09-26 09:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0005_student_student_id"),
        ("web", "0005_assignment_assignment_id_classtest_test_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="assignments/"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="question",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignment",
            name="total_marks",
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classtest",
            name="assign_to",
            field=models.ManyToManyField(blank=True, to="main.student"),
        ),
        migrations.AddField(
            model_name="classtest",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="class_tests/"),
        ),
        migrations.AddField(
            model_name="classtest",
            name="due_date",
            field=models.DateField(default=datetime.datetime(2024, 9, 26, 9, 57, 31, 914314, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classtest",
            name="test_duration",
            field=models.PositiveIntegerField(default=100, verbose_name="Test Duration (in minutes)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classtest",
            name="total_marks",
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="TestQuestion",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("question", models.TextField()),
                ("marks", models.PositiveIntegerField()),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("test", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.classtest")),
            ],
            options={
                "verbose_name": "Test Question",
                "verbose_name_plural": "Test Questions",
            },
        ),
        migrations.CreateModel(
            name="TestAnswer",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("answer", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.testquestion")),
            ],
            options={
                "verbose_name": "Test Answer",
                "verbose_name_plural": "Test Answers",
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("marks", models.PositiveIntegerField()),
                ("submission_date", models.DateField(auto_now_add=True)),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.assignment")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.student")),
            ],
            options={
                "verbose_name": "Assignment Submission",
                "verbose_name_plural": "Assignment Submissions",
            },
        ),
    ]
