# Generated by Django 4.2.9 on 2024-09-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_assignment_attachment_assignment_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testanswer",
            name="answer",
            field=models.CharField(max_length=200),
        ),
    ]
