# Generated by Django 4.2.9 on 2024-09-28 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_alter_testanswer_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testanswer",
            name="question",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="web.testquestion"),
        ),
    ]
