# Generated by Django 4.2.9 on 2024-09-29 01:56

from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_alter_testanswer_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="assignment_id",
            field=models.CharField(default=web.models.gen_assignment_id, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="assignment",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="web.assignment"),
        ),
        migrations.AlterField(
            model_name="classtest",
            name="test_id",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
