# Generated by Django 4.2.9 on 2024-09-29 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_alter_assignment_assignment_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="submission_date",
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="attachment",
            field=models.FileField(default=1, upload_to="assignment_submissions/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="marks",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
