# Generated by Django 4.2.9 on 2024-09-29 09:34

from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_remove_assignmentsubmission_submission_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classtest",
            old_name="assign_to",
            new_name="assigned_to",
        ),
        migrations.AddField(
            model_name="assignment",
            name="instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="classtest",
            name="test_id",
            field=models.CharField(default=web.models.gen_test_id, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="testquestion",
            name="test",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="web.classtest"),
        ),
    ]
