# Generated by Django 4.2.9 on 2024-09-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0011_rename_assign_to_classtest_assigned_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classtest",
            name="instructions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
