# Generated by Django 4.2.9 on 2024-09-29 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_student_student_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0012_classtest_instructions"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestSubmission",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.student")),
                ("test", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="web.classtest")),
            ],
            options={
                "verbose_name": "Test Submission",
                "verbose_name_plural": "Test Submissions",
            },
        ),
        migrations.CreateModel(
            name="TestAnswerSubmission",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("answer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.testanswer")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.testquestion")),
                ("submission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="web.testsubmission")),
            ],
            options={
                "verbose_name": "Test Answer Submission",
                "verbose_name_plural": "Test Answer Submissions",
            },
        ),
    ]
