# Generated by Django 4.2.9 on 2024-09-30 14:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0013_testsubmission_testanswersubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="instructions",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="classtest",
            name="instructions",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
