# Generated by Django 4.2.9 on 2024-09-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_student_student_id"),
        ("web", "0014_alter_assignment_instructions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="is_valuated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testsubmission",
            name="is_valuated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="student",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignment_submissions_student", to="main.student"),
        ),
    ]
