# Generated by Django 4.2.9 on 2024-10-01 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid
import web.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0006_alter_subject_standard"),
        ("web", "0015_assignmentsubmission_is_valuated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeTest",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("test_id", models.CharField(default=web.models.gen_test_id, max_length=200, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("due_date", models.DateField()),
                ("test_duration", models.PositiveIntegerField(verbose_name="Practice Duration (in minutes)")),
                ("total_marks", models.PositiveIntegerField()),
                ("attachment", models.FileField(blank=True, null=True, upload_to="class_tests/")),
                ("instructions", tinymce.models.HTMLField(blank=True, null=True)),
                ("assigned_to", models.ManyToManyField(blank=True, to="main.student")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="practice_test_created_by", to="main.teacher")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.subject")),
            ],
            options={
                "verbose_name": "Practice Test",
                "verbose_name_plural": "Practice Tests",
            },
        ),
        migrations.CreateModel(
            name="PracticeTestAnswer",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("answer", models.CharField(max_length=200)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Practice Answer",
                "verbose_name_plural": "Practice Answers",
            },
        ),
        migrations.CreateModel(
            name="PracticeTestSubmission",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("is_valuated", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.student")),
                ("test", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="web.practicetest")),
            ],
            options={
                "verbose_name": "Practice Submission",
                "verbose_name_plural": "Practice Submissions",
            },
        ),
        migrations.CreateModel(
            name="PracticeTestQuestion",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("question", models.TextField()),
                ("marks", models.PositiveIntegerField()),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("test", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="web.practicetest")),
            ],
            options={
                "verbose_name": "Practice Question",
                "verbose_name_plural": "Practice Questions",
            },
        ),
        migrations.CreateModel(
            name="PracticeTestAnswerSubmission",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("answer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.practicetestanswer")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.practicetestquestion")),
                ("submission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="web.practicetestsubmission")),
            ],
            options={
                "verbose_name": "Practice Answer Submission",
                "verbose_name_plural": "Practice Answer Submissions",
            },
        ),
        migrations.AddField(
            model_name="practicetestanswer",
            name="question",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="web.practicetestquestion"),
        ),
    ]
