# Generated by Django 4.2.9 on 2024-10-02 00:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0016_practicetest_practicetestanswer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practicetest",
            name="assigned_to",
        ),
    ]
