# Generated by Django 4.2.9 on 2024-10-05 22:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_notification"),
        ("web", "0017_remove_practicetest_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="events/"),
        ),
        migrations.AddField(
            model_name="event",
            name="content",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="time",
            field=models.TimeField(default=datetime.datetime(2024, 10, 5, 22, 0, 43, 642255, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="venue",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testsubmission",
            name="student",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="test_submissions_student", to="main.student"),
        ),
    ]
