# Generated by Django 4.2.9 on 2024-10-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0018_event_attachment_event_content_event_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="practicetestsubmission",
            old_name="is_valuated",
            new_name="is_completed",
        ),
        migrations.AddField(
            model_name="practicetestsubmission",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="practicetestsubmission",
            name="is_started",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testsubmission",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testsubmission",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testsubmission",
            name="is_started",
            field=models.BooleanField(default=False),
        ),
    ]
