# Generated by Django 4.2.9 on 2024-11-04 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid
import web.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0007_notification"),
        ("web", "0019_rename_is_valuated_practicetestsubmission_is_completed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockTest",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("test_id", models.CharField(default=web.models.gen_test_id, max_length=200, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("test_duration", models.PositiveIntegerField(verbose_name="Mock Test Duration (in minutes)")),
                ("total_marks", models.PositiveIntegerField()),
                ("attachment", models.FileField(blank=True, null=True, upload_to="class_tests/")),
                ("instructions", tinymce.models.HTMLField(blank=True, null=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mock_test_created_by", to="main.teacher")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.subject")),
            ],
            options={
                "verbose_name": "Mock Test",
                "verbose_name_plural": "Mock Tests",
            },
        ),
        migrations.CreateModel(
            name="MockTestAnswer",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("answer", models.CharField(max_length=200)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mock Answer",
                "verbose_name_plural": "Mock Answers",
            },
        ),
        migrations.CreateModel(
            name="MockTestSubmission",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("session_id", models.CharField(max_length=200, unique=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_started", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("test", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mock_submissions", to="web.mocktest")),
            ],
            options={
                "verbose_name": "Mock Submission",
                "verbose_name_plural": "Mock Submissions",
            },
        ),
        migrations.CreateModel(
            name="MockTestQuestion",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("question", models.TextField()),
                ("marks", models.PositiveIntegerField()),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("test", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mock_questions", to="web.mocktest")),
            ],
            options={
                "verbose_name": "Mock Question",
                "verbose_name_plural": "Mock Questions",
            },
        ),
        migrations.CreateModel(
            name="MockTestAnswerSubmission",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("answer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.mocktestanswer")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.mocktestquestion")),
                ("submission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mock_answers", to="web.mocktestsubmission")),
            ],
            options={
                "verbose_name": "Mock Answer Submission",
                "verbose_name_plural": "Mock Answer Submissions",
            },
        ),
        migrations.AddField(
            model_name="mocktestanswer",
            name="question",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mock_answers", to="web.mocktestquestion"),
        ),
    ]
