# Generated by Django 4.2.9 on 2024-11-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0020_mocktest_mocktestanswer_mocktestsubmission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mocktestsubmission",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mocktestsubmission",
            name="mobile_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mocktestsubmission",
            name="name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mocktestsubmission",
            name="school",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mocktestsubmission",
            name="session_id",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
