# Generated by Django 4.2.9 on 2025-03-23 17:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Coupon Name')),
                ('code', models.CharField(max_length=200, unique=True, verbose_name='Coupon Code')),
                ('discount', models.FloatField(verbose_name='Discount')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportedData',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(verbose_name='Data')),
                ('success_data', models.JSONField(blank=True, null=True, verbose_name='Success Data')),
                ('failed_data', models.JSONField(blank=True, null=True, verbose_name='Failed Data')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_imported', models.BooleanField(default=False, verbose_name='Is Imported')),
                ('imported_count', models.IntegerField(blank=True, null=True, verbose_name='Imported Count')),
                ('failed_count', models.IntegerField(blank=True, null=True, verbose_name='Failed Count')),
                ('time_taken', models.DurationField(blank=True, null=True, verbose_name='Time Taken')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='School Name')),
                ('place', models.CharField(max_length=200, verbose_name='Place')),
                ('district', models.CharField(max_length=200, verbose_name='District')),
                ('pin_code', models.CharField(max_length=200, verbose_name='Pin code')),
                ('poc_name', models.CharField(max_length=200, verbose_name='POC Name')),
                ('contact_number', models.CharField(max_length=200, verbose_name='Contact Number')),
                ('email_id', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('screenshot', models.FileField(upload_to='screenshots/', verbose_name='Screenshot')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Student Name')),
                ('student_class', models.CharField(max_length=200, verbose_name='Class')),
                ('syllabus', models.CharField(max_length=200, verbose_name='Syllabus')),
                ('school_name', models.CharField(max_length=200, verbose_name='School Name')),
                ('school_place', models.CharField(max_length=200, verbose_name='School Place')),
                ('parent_name', models.CharField(max_length=200, verbose_name='Parent Name')),
                ('place', models.CharField(max_length=200, verbose_name='Place')),
                ('pin_code', models.CharField(max_length=200, verbose_name='Pin code')),
                ('district', models.CharField(max_length=200, verbose_name='District')),
                ('contact_number', models.CharField(max_length=200, verbose_name='Contact Number')),
                ('whatsapp_number', models.CharField(max_length=200, verbose_name='WhatsApp Number')),
                ('email_id', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('preferred_language', models.CharField(max_length=200, verbose_name='Preferred Language')),
                ('preferred_exam_centre', models.CharField(max_length=200, verbose_name='Preferred Exam Centre')),
                ('register_number', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Register Number')),
                ('coupon', models.CharField(blank=True, max_length=200, null=True, verbose_name='Coupon (optional)')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='Razorpay Order ID')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='Razorpay Payment ID')),
                ('razorpay_signature', models.CharField(blank=True, max_length=128, null=True, verbose_name='Razorpay Signature ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('is_message_sent', models.BooleanField(default=False, verbose_name='Is Message Sent')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('is_imported', models.BooleanField(default=False, verbose_name='Is Imported')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='mydocs/', verbose_name='Document')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
