# Generated by Django 4.0.3 on 2022-06-14 06:59

import uuid

import django.core.validators
import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(upload_to="images/Products", verbose_name="Image"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=4.5,
                        max_digits=2,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(0.5),
                        ],
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("description", models.TextField()),
                ("is_hotproduct", models.BooleanField(default=False)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.category")),
            ],
        ),
        migrations.CreateModel(
            name="ProductEnquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(max_length=30)),
                ("message", models.TextField()),
                ("is_checked", models.BooleanField(default=False)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product")),
            ],
        ),
        migrations.CreateModel(
            name="OfferProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("offer_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("offer_startdate", models.DateField()),
                ("offer_enddate", models.DateField()),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product")),
            ],
        ),
    ]
