# Generated by Django 4.2.5 on 2025-05-17 07:53

import uuid

import django.db.models.deletion
import django_ckeditor_5.fields
import django_countries.fields
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("program_type", models.CharField(choices=[("ACADEMIC", "ACADEMIC COURSE"), ("LANGUAGE", "LANGUAGE COURSE")], default="ACADEMIC", max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("logo", models.ImageField(blank=True, null=True, upload_to="program/")),
                ("image", models.ImageField(upload_to="program/")),
                ("content", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ("lessons", models.IntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=200, null=True)),
                ("duration", models.CharField(blank=True, max_length=200, null=True)),
                ("preview_video_id", models.CharField(blank=True, max_length=11, null=True)),
                ("show_in_navigation", models.BooleanField(blank=True, default=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("meta_title", models.CharField(max_length=200)),
                ("meta_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("phone_number", models.CharField(max_length=25, verbose_name="Phone Number")),
                ("whatsapp_number", models.CharField(max_length=25, verbose_name="WhatsApp Number")),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("message", models.TextField(blank=True, null=True, verbose_name="Drop your message here")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("utm_source", models.CharField(blank=True, max_length=255, null=True)),
                ("utm_medium", models.CharField(blank=True, max_length=255, null=True)),
                ("utm_campaign", models.CharField(blank=True, max_length=255, null=True)),
                ("utm_content", models.CharField(blank=True, max_length=255, null=True)),
                ("utm_term", models.CharField(blank=True, max_length=255, null=True)),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("otp_number", models.CharField(blank=True, max_length=6, null=True)),
                ("attempt", models.IntegerField(default=0)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_sent2crm", models.BooleanField(default=False)),
                ("lsq_status_code", models.IntegerField(blank=True, null=True)),
                ("lsq_status", models.CharField(blank=True, max_length=200, null=True)),
                ("lsq_exception_type", models.TextField(blank=True, null=True)),
                ("lsq_exception_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Enquiry",
                "verbose_name_plural": "Enquiries",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "General FAQ",
                "verbose_name_plural": "General FAQs",
            },
        ),
        migrations.CreateModel(
            name="NonAcademicProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="program/")),
                ("program_type", models.CharField(choices=[("CLUB", "Club Courses"), ("NON_ACADEMIC", "Non Academic Courses")], default="ACADEMIC", max_length=200)),
                ("course_fee", models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ("duration", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "age_groups",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("3-5", "3-5 Years"),
                            ("6-9", "6-9 Years"),
                            ("10-13", "10-13 Years"),
                            ("14-18", "14-18 Years"),
                            ("18-20", "18-20 Years"),
                            ("20P", "20 Plus Years"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("lessons", models.IntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=200, null=True)),
                ("is_certificate_included", models.BooleanField(blank=True, default=True, null=True)),
                ("preview_video_id", models.CharField(blank=True, max_length=11, null=True)),
                ("content", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name="About")),
                ("learning_overview", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name="Learning Overview")),
                ("show_learning_overview", models.BooleanField(default=True, verbose_name="Show Learning Overview")),
                ("meta_title", models.CharField(max_length=200)),
                ("meta_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="slider/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Slider",
                "verbose_name_plural": "Sliders",
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("bi-instagram", "Instagram"),
                            ("bi-facebook", "Facebook"),
                            ("bi-youtube", "Youtube"),
                            ("bi-pinterest", "Pinterest"),
                            ("bi-twitter", "Twitter"),
                            ("bi-threads", "Threads"),
                            ("bi-tiktok", "Tiktok"),
                            ("bi-wikipedia", "Wikipedia"),
                            ("bi-google", "Google"),
                            ("bi-google-play", "Google Play"),
                            ("bi-github", "github"),
                            ("bi-xbox", "X Box"),
                            ("bi-linkedin", "Linkedin"),
                            ("bi-youtube", "Youtube"),
                        ],
                        max_length=200,
                    ),
                ),
                ("url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Media",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="testimonial/")),
                ("content", models.TextField()),
                ("video_id", models.CharField(max_length=11)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
        migrations.CreateModel(
            name="ProgramFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.academicprogram")),
            ],
            options={
                "verbose_name": "Program Feature",
                "verbose_name_plural": "Program Features",
            },
        ),
        migrations.CreateModel(
            name="ProgramFAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.academicprogram")),
            ],
            options={
                "verbose_name": "Program FAQ",
                "verbose_name_plural": "Program FAQs",
            },
        ),
        migrations.CreateModel(
            name="ProgramBenefit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.academicprogram")),
            ],
            options={
                "verbose_name": "Program Benefit",
                "verbose_name_plural": "Program Benefits",
            },
        ),
    ]
