# Generated by Django 4.2.5 on 2025-05-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="subject",
            field=models.CharField(default="Maths", max_length=200, verbose_name="Subject"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="slider",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Student Name"),
        ),
    ]
