# Generated by Django 4.2.9 on 2025-06-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_configuration_slider_subject_alter_slider_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('home_meta_title', 'Home Page Meta Title'), ('home_meta_desc', 'Home Page Meta Description'), ('littlegenie_meta_title', 'Little Genie Page Meta Title'), ('littlegenie_meta_desc', 'Little Genie Page Meta Description')], max_length=200, unique=True)),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
            },
        ),
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=25, verbose_name='Phone Number')),
                ('whatsapp_number', models.CharField(max_length=25, verbose_name='WhatsApp Number')),
                ('standard', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Data',
                'verbose_name_plural': 'Contact Data',
            },
        ),
    ]
