# Generated by Django 4.2.9 on 2025-06-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_configuration_contactdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactData',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='NonAcademicProgram',
        ),
        migrations.RemoveField(
            model_name='programbenefit',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programfaq',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programfeature',
            name='program',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='country',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='message',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='otp_number',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='token',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='page',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Page'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='standard',
            field=models.CharField(choices=[('LKG', 'LKG'), ('UKG', 'UKG'), ('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], default=1, max_length=10, verbose_name='Standard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(default=1, max_length=200, verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuration',
            name='key',
            field=models.CharField(choices=[('home_meta_title', 'Home Page Meta Title'), ('home_meta_desc', 'Home Page Meta Description'), ('littlegenie_meta_title', 'Little Genie Page Meta Title'), ('littlegenie_meta_desc', 'Little Genie Page Meta Description'), ('foundation_meta_title', 'Foundation Page Meta Title'), ('foundation_meta_desc', 'Foundation Page Meta Description')], max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='AcademicProgram',
        ),
        migrations.DeleteModel(
            name='ProgramBenefit',
        ),
        migrations.DeleteModel(
            name='ProgramFAQ',
        ),
        migrations.DeleteModel(
            name='ProgramFeature',
        ),
    ]
