# Generated by Django 4.2.9 on 2025-06-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_delete_contactdata_delete_faq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=25, verbose_name='Phone Number')),
                ('whatsapp_number', models.CharField(max_length=25, verbose_name='WhatsApp Number')),
                ('standard', models.CharField(choices=[('LKG', 'LKG'), ('UKG', 'UKG'), ('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=10, verbose_name='Standard')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sent2crm', models.BooleanField(default=False)),
                ('lsq_status_code', models.IntegerField(blank=True, null=True)),
                ('lsq_status', models.CharField(blank=True, max_length=200, null=True)),
                ('lsq_exception_type', models.TextField(blank=True, null=True)),
                ('lsq_exception_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
            },
        ),
        migrations.CreateModel(
            name='LGEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=25, verbose_name='Phone Number')),
                ('whatsapp_number', models.CharField(max_length=25, verbose_name='WhatsApp Number')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sent2crm', models.BooleanField(default=False)),
                ('lsq_status_code', models.IntegerField(blank=True, null=True)),
                ('lsq_status', models.CharField(blank=True, max_length=200, null=True)),
                ('lsq_exception_type', models.TextField(blank=True, null=True)),
                ('lsq_exception_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
            },
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
